[main]

# Training Configuration
embedding_folder = ../data/sample_dataset/5Attack/embedding  
n_splits = 5                       
epochs = 150                        
batch_size = 128                  
learning_rate = 0.0001             
early_stopping_patience = 10       
monitor_checkpoint = loss      
monitor_reduce_lr = val_loss       

# Model Configuration
dropout_rate = 0.2                
l1_l2_value = 0.01              
activation = relu                 
conv_block_count = 2               
[focal_loss]
gamma = 2.0                        
alpha = 0.25                       
epsilon = 1e-7                    


[reduce_lr]
factor = 0.1            
patience = 3            
min_lr =  0.01          
cooldown = 0