[paths]
clean_data_dir = C:/Users/s222343272/Downloads/datasets/clean_label/
data_sanitization_dir = C:/Users/s222343272/Downloads/datasets/test_test/
model_save_path = anomaly_autoencoder.h5
threshold_file = threshold.json
hubert_ckpt_path = ./hubert_base_ls960.pt
hubert_quantizer_path = ./hubert_base_ls960_L9_km500.bin



[training]
sampling_rate = 16000
n_mels = 40
max_length = 256
batch_size = 16
epochs = 50
validation_split = 0.15
anomaly_threshold_multiplier = 2

[sanitization]
wiener_enabled = True
bandstop_filter_enabled = True
max_time_mask = 0.05
max_freq_mask = 0.05




[main]

# Training Configuration
optimizer = Adam
loss = BinaryCrossentropy
metrics = accuracy,precision,recall
dropout_rate = 0.2
l1_l2_value = 0.01
activation = relu
conv_block_count = 2

# Main Model Parameters
embedding_folder = ../data/sample_dataset/5Attack/embedding
n_splits = 5
epochs = 300
batch_size = 128
class_weight_dict = {0: 0.1, 1: 15}
learning_rate = 0.0001
early_stopping_patience = 10
monitor_checkpoint = val_loss
monitor_reduce_lr = val_loss


[focal_loss]
gamma = 2.0
alpha = 0.25
epsilon = 1e-7


; [main]

; # Model Configuration
; optimizer = adam
; activation = leaky_relu
; leaky_relu_alpha = 0.01
; loss = BinaryCrossentropy
; metrics = accuracy,precision,recall, AUC
; dropout_rate = 0
; batch_norm = True
; l1_l2_value = 0
; conv_block_count = 3

; # Training Parameters
; embedding_folder = ../data/sample_dataset/libri_data/wav_lib/embedding_10/
; n_splits = 5
; epochs = 200
; batch_size = 128
; class_weight_dict = {0: 1, 1: 5}
; #class_weight_dict = auto
; learning_rate = 0.0001
; early_stopping_patience = 50
; monitor_checkpoint = val_loss
; monitor_reduce_lr = val_loss


; [focal_loss]
; gamma = 2.5
; alpha = 1
; epsilon = 1e-7


